---
- hosts: all
  become: yes
  roles: 
    - get-source

- hosts: zookeeper
  become: yes
  roles: 
    - zookeeper

- hosts: kafka
  become: yes
  roles: 
    - kafka

- hosts: kafka-client
  become: yes
  roles: 
    - kafka-mirror
    - kafka-manager
