---
- name: Add or modify hard nofile limits for wildcard domain
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: 100000

- name: create directory /data/kafka/
  file: 
    dest: /data/kafka/
    state: directory

- name: Remove file consumer.properties
  file:
    path: /opt/kafka/config/consumer.properties
    state: absent

- name: Remove file producer.properties
  file:
    path: /opt/kafka/config/producer.properties
    state: absent

- name: configure consumer.properties
  template:
    src: consumer.properties.j2
    dest: /opt/kafka/config/consumer.properties

- name: configure producer.properties
  template:
    src: producer.properties.j2
    dest: /opt/kafka/config/producer.properties

- name: configure kafka.service
  template:
    src: kafka-mirror.service.j2
    dest: /etc/systemd/system/kafka-mirror.service
  
- name: start kafka
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kafka