---
- name: install common packages
  apt:
    name:
      - ntp
      - vim
      - htop
      - nmon
      - sudo
      - net-tools
      - wget
      - ca-certificates
      - zip
      - net-tools
      - tar
      - netcat
      - openjdk-8-jdk
      - apt-transport-https
      - curl
      - gnupg2 
      - software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: disbale ram swap
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present

- name: set all of nodes to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '{{ "%-15s" | format(hostvars[item].ansible_host) }}        {{ item }}'
    state: present
  with_items: "{{ ansible_play_hosts }}"
  when: hostvars[item].ansible_host is defined

- name: create directory /opt/
  file: 
    dest: /opt/
    state: directory

- name: download sources
  get_url: 
    url: https://archive.apache.org/dist/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz 
    dest: /opt/

- name: Extract 
  unarchive:
    src: /opt/kafka_2.12-0.10.2.1.tgz 
    dest: /opt/kafka
    remote_src: yes
  
#- name: Rename kafka dir 
#  command: mv /opt/kafka_2.12-0.10.2.1 /opt/kafka
#  ignore_errors: yes