---
- name: Add docker apt-key
  apt_key:
      url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
      state: present
- apt_repository:
    repo:    "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
- name: install docker packages
  apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: yes
    cache_valid_time: 3600